name: Flask CI
description: "Run Flask app checks on push to master branch"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask

      - name: Check Flask app
        run: |
          # Start Flask app
          python app.py &
          sleep 5
          # Make request to Flask app
          curl http://127.0.0.1:5000

      - name: Stop Flask app
        run: pkill -f "python app.py"
